workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Spaire-OAS:
        inputs:
            - location: https://api.polar.sh/openapi.json
        overlays:
            - location: https://raw.githubusercontent.com/polarsource/polar/main/sdk/overlays/security.yml
            - location: https://raw.githubusercontent.com/polarsource/polar/main/sdk/overlays/type_parameter.yml
            - location: https://raw.githubusercontent.com/polarsource/polar/main/sdk/overlays/read_only.yml
            - location: https://raw.githubusercontent.com/polarsource/polar/main/sdk/overlays/event_discriminator.yml
            - location: https://raw.githubusercontent.com/polarsource/polar/main/sdk/overlays/timezone_enum.yml
            - location: https://raw.githubusercontent.com/polarsource/polar/main/sdk/overlays/event_metadata.yml
        registry:
            location: registry.speakeasyapi.dev/spaire/spaire/spaire-oas
targets:
    spaire:
        target: python
        source: Spaire-OAS
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/spaire/spaire/spaire-oas-py-code-samples
            labelOverride:
                fixedValue: Python (SDK)
