"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from spaire_sdk.customer_session_sdk import CustomerSessionSDK
from spaire_sdk.downloadables import Downloadables
from spaire_sdk.spaire_benefit_grants import SpaireBenefitGrants
from spaire_sdk.spaire_customer_meters import SpaireCustomerMeters
from spaire_sdk.spaire_customers import SpaireCustomers
from spaire_sdk.spaire_license_keys import SpaireLicenseKeys
from spaire_sdk.spaire_orders import SpaireOrders
from spaire_sdk.spaire_organizations import SpaireOrganizations
from spaire_sdk.spaire_subscriptions import SpaireSubscriptions
from spaire_sdk.seats import Seats
from spaire_sdk.wallets import Wallets
from typing import Optional


class CustomerPortal(BaseSDK):
    benefit_grants: SpaireBenefitGrants
    customers: SpaireCustomers
    customer_meters: SpaireCustomerMeters
    seats: Seats
    customer_session: CustomerSessionSDK
    downloadables: Downloadables
    license_keys: SpaireLicenseKeys
    orders: SpaireOrders
    organizations: SpaireOrganizations
    subscriptions: SpaireSubscriptions
    wallets: Wallets

    def __init__(
        self, sdk_config: SDKConfiguration, parent_ref: Optional[object] = None
    ) -> None:
        BaseSDK.__init__(self, sdk_config, parent_ref=parent_ref)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.benefit_grants = SpaireBenefitGrants(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.customers = SpaireCustomers(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.customer_meters = SpaireCustomerMeters(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.seats = Seats(self.sdk_configuration, parent_ref=self.parent_ref)
        self.customer_session = CustomerSessionSDK(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.downloadables = Downloadables(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.license_keys = SpaireLicenseKeys(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.orders = SpaireOrders(self.sdk_configuration, parent_ref=self.parent_ref)
        self.organizations = SpaireOrganizations(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.subscriptions = SpaireSubscriptions(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.wallets = Wallets(self.sdk_configuration, parent_ref=self.parent_ref)
