"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from spaire_sdk.models import SpaireError
from spaire_sdk.types import BaseModel
from spaire_sdk.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated


class NotOpenCheckoutData(BaseModel):
    detail: str

    ERROR: Annotated[
        Annotated[
            Literal["NotOpenCheckout"],
            AfterValidator(validate_const("NotOpenCheckout")),
        ],
        pydantic.Field(alias="error"),
    ] = "NotOpenCheckout"


@dataclass(unsafe_hash=True)
class NotOpenCheckout(SpaireError):
    data: NotOpenCheckoutData = field(hash=False)

    def __init__(
        self,
        data: NotOpenCheckoutData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
