"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from spaire_sdk.types import BaseModel
from spaire_sdk.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class ProductPriceFreeCreateTypedDict(TypedDict):
    r"""Schema to create a free price."""

    amount_type: Literal["free"]


class ProductPriceFreeCreate(BaseModel):
    r"""Schema to create a free price."""

    AMOUNT_TYPE: Annotated[
        Annotated[Literal["free"], AfterValidator(validate_const("free"))],
        pydantic.Field(alias="amount_type"),
    ] = "free"
